spring.application.name=bff
server.port=8080
auth.service.url=${AUTH_SERVICE_URL:http://localhost:8081}
user.service.url=${USER_SERVICE_URL:http://localhost:8082}
message.service.url=${MESSAGE_SERVICE_URL:http://localhost:8083}
bot.service.url=${BOT_SERVICE_URL:http://localhost:8084}

//security.jwt.secret=mysupersecretkeymysupersecretkey123456

security.jwt.secret=${SECURITY_JWT_SECRET:mysupersecretkeymysupersecretkey123456}