spring.application.name=bff
server.port=8080
auth.service.url=http://localhost:8081
user.service.url=http://localhost:8082
message.service.url=http://localhost:8083
bot.service.url=http://localhost:8084

security.jwt.secret=mysupersecretkeymysupersecretkey123456